{% set version = "1.5.2" %}

package:
  name: nose-progressive
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nose-progressive/nose-progressive-{{ version }}.tar.gz
  sha256: 3a6e2833e613c1c239baf05a19f66b5920915e62c07251d3ab3f3acb017ef5d7

build:
  number: 1001
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - nose >=1.2.1  
    - blessings >=1.3,<2.0

test:
  imports:
    - noseprogressive

about:
  home: https://github.com/erikrose/nose-progressive
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A nosetests plugin with a progress bar and an emphasis on showing what is important'
  description: |
    nose-progressive is a nose plugin which displays progress in a stationary bar, 
    freeing the rest of the screen (as well as the scrollback buffer) for the 
    compact display of test failures, which it formats beautifully and usefully.   
  doc_url: https://github.com/erikrose/nose-progressive
  dev_url: https://github.com/erikrose/nose-progressive

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
