appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vTGNlkHiwSWbxsglmMkuTeImge0DdFFxURdQKt4BgKELZHiBuamIgJYzpy7K1o8ii47neeHCBt1gj+Tu5ZKezexYUDXtBqEXCStneR4qksw2DRuuBN22JtzmPWfGIEWJQ2d5K7kzOwcar0JbngALIfjU2LPJZrIfDxJDxBXQaN1g4P87w/wyUnYIFJjoQ07pS3vxnS+S6Xw2g+/vxbbEZ1+U7NTLfXhQI6UlVwvZhYTg5QXePhCEnC1TUbLLxHlfdYPKseVga1FVybVU+3kbPlDs7C/87i1zujnY2pxW67IqqCYP6ofdb/cCAkIxAVIzhIVYWw46ZXvDi5KVe5w+CN1/73tM2nxFbDSfSc+Hv2UkCF7YVKIKNo4rq5c+7CEiGzj/4WzSNWEb8Na2jqgbrAJA4HyMW6Fljnqq7VjvZd/stZwbbv6tmu9lLY9TadWH+dJzvJU6EtOvAllYdSJMklUB+wNoygTzhmJfs3YA6N0I0CbeEg4jNfzbNGEtnZ3m3flKSS8CFWQlyIBbrjBgadvg5H14TvULwBumTUn45L3RtevqrBQVOHIJ7ydZR+7Nj5PONrs68rg4PkMmEL7s2y4d6qSVCx7kMvP3eQ6op2TT9yy806V0BXAP0HjOkH7KGs8O18ZnouDY24t2ADc8aBzGOWF3z/5DfL1h6Ku8YNw=}
conda_forge_output_validation: true
